In [4]:
!pip install numpy
!pip install pandas
!pip install



In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]


In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [7]:
myarr=np.array(my_list)

In [8]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
len(np.linspace(0,10,3))

3

In [22]:
np.eye(5)#identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(1)#returns any value from 0 to 1

array([0.58379006])

In [24]:
np.random.rand(5,6)

array([[0.91032724, 0.31531472, 0.18556041, 0.24022301, 0.71816751,
        0.78040983],
       [0.68431117, 0.39973225, 0.80566773, 0.64713978, 0.71633154,
        0.61068506],
       [0.7094831 , 0.60041748, 0.02507718, 0.81001073, 0.53103446,
        0.22751995],
       [0.28393874, 0.03652849, 0.21294101, 0.71139338, 0.88854626,
        0.44357116],
       [0.18266139, 0.45471706, 0.36550214, 0.98163153, 0.99474641,
        0.54706713]])

In [26]:
np.random.randn(10)
#it gives 10 random numbers from standard normal distribution of mean=0 and variance=1

array([-0.45744929,  0.16277725, -1.11413127, -0.39443342, -1.46416407,
       -0.54021996,  1.16974002, -0.85424144, -1.67127686,  0.45199292])

In [27]:
np.random.randint(0,101,5)

array([97, 73, 24, 73, 15])

In [30]:
np.random.seed(42)

In [31]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
#reshaping
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr=np.random.randint(0,101,10)
arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [37]:
arr.min()

2

In [38]:
arr.max()

99

In [39]:
arr.argmax()
#returns index of the max value

5

In [41]:
arr.argmin()

7

In [42]:
arr.dtype #calling datatype

dtype('int32')

In [43]:
arr.shape

(10,)

In [44]:
#numpy array indexing and slicing
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[3]

3

In [46]:
arr[8]

8

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[5:]

array([5, 6, 7, 8, 9])

In [49]:
arr=np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [52]:
arr[0:2]=24

In [53]:
arr

array([24, 24,  2,  3,  4])

In [55]:
A=np.arange(1,5)

In [56]:
A

array([1, 2, 3, 4])

In [57]:
A>2

array([False, False,  True,  True])

In [58]:
bool_A=A>2
A[bool_A]

array([3, 4])

In [63]:
#numpy operations
A=np.arange(1,5)
A

array([1, 2, 3, 4])

In [66]:
A+A

array([10, 12, 14, 16])

In [67]:
A+5

array([10, 11, 12, 13])

In [68]:
A-2

array([3, 4, 5, 6])

In [69]:
A*A

array([25, 36, 49, 64])

In [70]:
A/2

array([2.5, 3. , 3.5, 4. ])

In [71]:
np.sqrt(A)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [72]:
A.sum()

26

In [73]:
A.mean()

6.5

In [74]:
np.log(A)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [75]:
A.max()

8

In [76]:
A.var()

1.25

In [77]:
A2d=np.arange(1,5).reshape(2,2)
A2d

array([[1, 2],
       [3, 4]])

In [78]:
A2d.sum()

10

In [79]:
A2d.sum(axis=0)

array([4, 6])

In [80]:
A2d.sum(axis=1)

array([3, 7])